### CADASTRAR ABRIGO
POST http://localhost:5286/adopet/abrigos/cadastrar
Content-Type: application/json

{
    "nome": "Abrigo São Francisco",
    "localizacao": "Rua A, 123",
    "telefone": "123456789"
}

### LISTAR ABRIGOS
GET http://localhost:5286/adopet/abrigos/listar
Accept: application/json

### CADASTRAR ANIMAL
POST http://localhost:5286/adopet/animais/cadastrar
Content-Type: application/json

{
    "nome": "Rex",
    "especie": "Cachorro",
    "raca": "Labrador",
    "idade": 5,
    "disponivelParaAdocao": true,
    "abrigoId": 1
}

### LISTAR ANIMAIS
GET http://localhost:5286/adopet/animais/listar
Accept: application/json

### EXCLUIR ANIMAL
DELETE http://localhost:5286/adopet/animais/13

### CADASTRAR ADOTANTE
POST http://localhost:5286/adopet/adotantes/cadastrar
Content-Type: application/json

{
    "nome": "Alisson"
}

### LISTAR ADOTANTES
GET http://localhost:5286/adotantes/listar
Accept: application/json

### CADASTRAR ADOÇÃO
POST http://localhost:5286/adopet/adocoes/cadastrar
Content-Type: application/json

{
    "adotanteId": 1,
    "animalId": 1,
    "dataAdocao": "2024-10-18T14:30:00",
    "status": "Pendente"
}

### LISTAR ADOÇÕES
GET http://localhost:5286/adocoes/listar
Accept: application/json

### EXCLUIR ADOÇÃO
DELETE http://localhost:5286/adocoes/1