### CADASTRAR ANIMAL
POST http://localhost:5286/adopet/animais/cadastrar
Content-Type: application/json

{
    "nome": "Bruce",
    "especie": "Cachorro",
    "raca": "Pitbull",
    "idade": 6,
    "disponivelParaAdocao": true,
    "abrigoId": 1
}

### CADASTRAR ABRIGO
POST http://localhost:5286/adopet/abrigos/cadastrar
Content-Type: application/json

{
    "nome": "Abrigo São Jose de Paula",
    "localizacao": "Rua XVI, 25",
    "telefone": "123456789"
}

### CADASTRAR ADOTANTE
POST http://localhost:5286/adopet/adotantes/cadastrar
Content-Type: application/json

{
    "nome": "Tiringa",
    "email": "tiringadafaca@gmail.com"
}

### CADASTRAR ADOÇÃO
POST http://localhost:5286/adopet/adocoes/cadastrar
Content-Type: application/json

{
    "adotanteId": 1,
    "animalId": 1,
    "nome": "Alisson",
    "dataAdocao": "2024-10-18T14:30:00",
    "status": "Aprovado"
}

### ATUALIZAR ANIMAIS
PUT http://localhost:5286/adopet/animais/3
Content-Type: application/json

{
    "nome": "Mario",
    "especie": "Gato",
    "raca": "Siamês",
    "idade": 2,
    "disponivelParaAdocao": false,
    "abrigoId": 1
}

### LISTAR ANIMAIS
GET http://localhost:5286/adopet/animais/listar
Accept: application/json

### LISTAR ABRIGOS
GET http://localhost:5286/adopet/abrigos/listar
Accept: application/json

### LISTAR ADOTANTES
GET http://localhost:5286/adopet/adotantes/listar
Accept: application/json

### LISTAR ADOÇÕES
GET http://localhost:5286/adopet/adocoes/listar
Accept: application/json

### EXCLUIR ANIMAL
DELETE http://localhost:5286/adopet/animais/3

### EXCLUIR ABRIGO
DELETE http://localhost:5286/adopet/abrigos/30

### EXCLUIR ADOÇÕES
DELETE http://localhost:5286/adopet/adocoes/

### EXCLUIR ADOTANTES
DELETE  http://localhost:5286/adopet/adotantes/4
